name: Deploy Images to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@v3
      
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
      
          - name: "Login to DockerHub"
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
      
          - name: "Build and Push Telegram Bot"
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: curiousdima/pardonmyenglish:latest
              platforms: linux/amd64, linux/arm64
