name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        defaults:
          run:
            working-directory: './telegram-bot'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@v4

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Telegram Bot Image'
            run: |
              docker build . --tag ghcr.io/curiousdima/pardon-my-english:latest
              docker push ghcr.io/curiousdima/pardon-my-english:latest
